### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PATRIK8588** [SoRadGaming/Auto-Youtube-Shorts-Scroller#11]
It has worked for me before, but now it does not scroll after the end of the short. When the short ended it just pauses the video. It stopped working for me about 2 weeks ago, but i thought it would fix itself. I also tried reinstalling the extension, but no sucess.

**Comment by Vvaltz** [comment]
can confirm, check that new class name is "reel-video-in-sequence-new" instead of "reel-video-in-sequence", @SoRadGaming

**Comment by PATRIK8588** [comment]
And how could i fix it?

**Comment by Vvaltz** [comment]
maybe like this ? 
const VIDEOS_LIST_SELECTOR = ".reel-video-in-sequence";
->
const VIDEOS_LIST_SELECTOR = ".reel-video-in-sequence-new";

**Comment by madmack1** [comment]
will this be updated? No longer works for me either

**Comment by reyard** [comment]
It needs new update

**Comment by Nipsy90** [comment]
I fixed it including updating it completely from the original chromium extension. Works fine on my end again, you just have to wait for @SoRadGaming to merge it and update the mozilla extension on mozillas addon sites (or temporarily get an unsigned extension from my fork at your own risk)

**Comment by SoRadGaming** [comment]
Sorry guys just saw this, working on updated port now, i didnt relise the automated workflow failed

**Comment by Nipsy90** [comment]
feel free to take anything from my pull request

**Comment by SoRadGaming** [comment]
Fixed thx @Nipsy90

**Comment by Nipsy90** [comment]
there still seems to be something wrong with your current code since your release still doesn't work for me. 
Not sure what you took from my pull request in the end since I basically just resolved the errors the chromium version gave me on tsc for firefox which worked for me in the end (of course with different looks etc)
